id: A9C4417B8
title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the Sixty
  Solitary Forms of Yamāntaka
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:36:36.232455
  last_modified_at: 2022-03-01 06:36:36.232459
