id: A9C4417B8
title: Daily Practice of Mañjuśrī Yamāntaka
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:36:36.229873
  last_modified_at: 2022-03-01 06:36:36.229880
